version: '2.0'
services:
  #PHP Service
  app:
    build:
      args:
        user: ryan
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: blogapp
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    tty: true
    working_dir: /var/www/
 
  #Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./:/var/www/
      - ./nginx:/etc/nginx/conf.d
    tty: true
    ports:
      - "8000:80"
    expose:
      - "80"
      - "8000"
  
  # Database visualizer
  adminer:
    image: adminer:latest
    container_name: adminer_sql
    restart: always
    ports:
      - 8080:8080

  #MySQL Service
  db:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: blogapp
      MYSQL_ROOT_PASSWORD: admin
